### ISSUE TITLE
Only seeing last entry in bulk

### ISSUE THREAD

**Issue by hcsaustrup** [logstash-plugins/logstash-codec-es_bulk#12]
Trying to make Logstash accept ElasticSearch bulk requests, by using the es_bulk plugin. Only the last event (of three) seems to be processed.

This is my configuration:

```
input {
        http {
                port => 8089
                codec => "es_bulk"
        }
}
output {
        stdout { codec => rubydebug  }
}
```
This is how I post:

```
curl -XPOST --data-binary @- -H "Content-Type: application/json" "http://127.0.0.1:8089/_bulk" <<EOF
{"index":{"_index":"$_INDEX","_type":"logevent"}}
{"@timestamp":"$_TIME","level":"Information","message":"First entry"}
{"index":{"_index":"$_INDEX","_type":"logevent"}}
{"@timestamp":"$_TIME","level":"Information","message":"Second entry"}
{"index":{"_index":"$_INDEX","_type":"logevent"}}
{"@timestamp":"$_TIME","level":"Information","message":"Third entry"}
EOF
```

This is the ONLY log output:

```
{
    "@timestamp" => "2017-05-10T13:50:44.838Z",
         "level" => "Information",
       "message" => "Third entry",
      "@version" => "1",
          "host" => "127.0.0.1",
       "headers" => {
         "request_method" => "POST",
           "request_path" => "/_bulk",
            "request_uri" => "/_bulk",
           "http_version" => "HTTP/1.1",
        "http_user_agent" => "curl/7.29.0",
              "http_host" => "127.0.0.1:8089",
            "http_accept" => "*/*",
           "content_type" => "application/json",
         "content_length" => "469"
    }
}
```

I would expect to see all three log entries processed. It also seems like I'm missing some metadata, like the index name. Any ideas?

Version: Logstash 2.4.0
OS: RHEL 7.2 64bit

**Comment by bhatch4** [comment]
I have the same problem. 
With Logstash 2.4.1 I get the exact same symptoms as you. Only the final record shows up.
With Logstash 5.6.1 I see the headers of the first record, but the data itself doesn't make it in. Nothing at all shows up for the 2nd to Nth records. 
Using the exact same post request and posting to Elasticsearch itself works fine. It's just when posting to Logstash that records go missing.

**Comment by colinsurprenant** [comment]
@hcsaustrup @bhatch4 this problem is related to the `codec` vs `additional_codecs` options in the http input. The configured codecs in `additional_codecs` are prioritized over the `codec` option and by default `additional_codecs` is set to `{ "application/json" => "json" }` which means that regardless of what you set in the `codec` option `application/json` content type will always be handled by the `json` codec. 

There are 2 ways to solve this;

- clear `additional_codecs` : 
```
input{http{port => 8080 additional_codecs => {} codec => es_bulk}}
```

- set `additional_codecs` : 
```
input{http{port => 8080 additional_codecs => { "application/json" => "es_bulk" } }}
```

Let me know if that work for you. I will fo ahead and close that issue, feel free to reopen if needed.

**Comment by Alsheh** [comment]
I get a 500 response with logstash `7.9.3`:
input:
```
input{http{port => 8080 additional_codecs => {} codec => es_bulk}}
```
Request#1:
```
curl -X POST <hostname> -H 'Content-Type: application/json' -d'
{ "index" : { "_index" : "test", "_id" : "1" } }
{ "field1" : "value1" }
{ "delete" : { "_index" : "test", "_id" : "2" } }
{ "create" : { "_index" : "test", "_id" : "3" } }
{ "field1" : "value3" }
{ "update" : {"_id" : "1", "_index" : "test"} }
{ "doc" : {"field2" : "value2"} }
```

Request#2:
```
curl -X POST <hostname> -H 'Content-Type: application/json' -d'
{ "index" : { "_index" : "test", "_id" : "1" } }
{ "field1" : "value1" }
{ "delete" : { "_index" : "test", "_id" : "2" } }
{ "create" : { "_index" : "test", "_id" : "3" } }
{ "field1" : "value3" }
{ "update" : {"_id" : "1", "_index" : "test"} }
{ "doc" : {"field2" : "value2"} }
```

Response: Both request attempts give a 500 response.

Logstash logs:
```
3/25/2021 2:31:31 AM[2021-03-24T23:31:31,583][ERROR][logstash.inputs.http     ][main][89eb10bbe5ff98c934d746fe7912209e2c14523b78301bb19130acb95d5b3d36] unable to process event. {:message=>"undefined method `keys' for nil:NilClass", :class=>"NoMethodError", :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-codec-es_bulk-3.0.8/lib/logstash/codecs/es_bulk.rb:35:in `block in decode'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-codec-line-3.0.8/lib/logstash/codecs/line.rb:38:in `block in decode'", "org/jruby/RubyArray.java:1809:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-codec-line-3.0.8/lib/logstash/codecs/line.rb:38:in `decode'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-codec-es_bulk-3.0.8/lib/logstash/codecs/es_bulk.rb:25:in `decode'", "/usr/share/logstash/logstash-core/lib/logstash/codecs/delegator.rb:62:in `block in decode'", "org/logstash/instrument/metrics/AbstractSimpleMetricExt.java:65:in `time'", "org/logstash/instrument/metrics/AbstractNamespacedMetricExt.java:64:in `time'", "/usr/share/logstash/logstash-core/lib/logstash/codecs/delegator.rb:61:in `decode'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-http-3.3.5-java/lib/logstash/inputs/http.rb:166:in `decode_body'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-http-3.3.5-java/lib/logstash/inputs/http/message_handler.rb:26:in `onNewMessage'"]}
```
